language: node_js
cache:
  directories:
    - node_modules
addons:
  firefox: "45.0"
node_js:
  - "4"
  - "6"
before_script:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - 'npm install'
after_success: npm run coveralls
webhooks:
  urls:
    - https://webhooks.gitter.im/e/2186a68c76bf266e2876
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: never     # options: [always|never|change] default: always
